export const VENDOR_DASHBOARD_FALLBACK = {
  stats: {
    totalSales: "$12,456.78",
    salesTodayLabel: "0.2% vs last week",
    orders: 248,
    ordersThisWeekLabel: "0.5% vs last week",
    productSold: 1245,
    productSoldLabel: "0.2% vs last week",
    totalCustomers: 358,
    customersAddedLabel: "0.2% vs last week",
  },
  metrics: {
    totalRevenue: "$12,456.78",
    totalExpenses: "$2,567.89",
    netEarnings: "$10,000.89",
  },
  orderStatus: [
    { id: 1, label: "Pending", count: "12 (16.2%)", color: "#0066CC" },
    { id: 2, label: "Confirmed", count: "28 (18.2%)", color: "#009900" },
    { id: 3, label: "Shipped", count: "10 (12.2%)", color: "#00CCFF" },
    { id: 4, label: "Delivered", count: "14 (18.2%)", color: "#FFD700" },
    { id: 5, label: "Cancelled", count: "34 (11.2%)", color: "#FF0000" },
  ],
  inventoryAlerts: [
    {
      id: 1,
      name: "Organic Spinach",
      sku: "SKU SPH 200",
      image: "https://via.placeholder.com/80",
      status: "Low Stock",
      stock: "Only 8 left",
    },
    {
      id: 2,
      name: "Fresh Strawberry",
      sku: "SKU SPH 200",
      image: "https://via.placeholder.com/80",
      status: "Low Stock",
      stock: "Only 12 left",
    },
    {
      id: 3,
      name: "Desi Potatoes",
      sku: "SKU SPH 200",
      image: "https://via.placeholder.com/80",
      status: "Low Stock",
      stock: "Only 7 left",
    },
  ],
  recentOrders: [
    {
      id: 1,
      orderId: "#ORD-1245",
      customer: "John Doe",
      amount: "$45.00",
      status: "Pending",
      date: "May 18, 2024",
    },
    {
      id: 2,
      orderId: "#ORD-1245",
      customer: "starmind",
      amount: "$335.00",
      status: "Confirmed",
      date: "May 18, 2024",
    },
    {
      id: 3,
      orderId: "#ORD-1245",
      customer: "kelvin victor",
      amount: "$645.00",
      status: "Shipped",
      date: "May 18, 2024",
    },
    {
      id: 4,
      orderId: "#ORD-1245",
      customer: "John Doe",
      amount: "$456.00",
      status: "Delivered",
      date: "May 18, 2024",
    },
    {
      id: 5,
      orderId: "#ORD-1245",
      customer: "matin Doe",
      amount: "$945.00",
      status: "Pending",
      date: "May 18, 2024",
    },
  ],
  topProducts: [
    {
      id: 1,
      name: "Fresh Strawberry (50kg)",
      image: "https://via.placeholder.com/150",
      sold: "234 sold",
      price: "$67.50",
    },
    {
      id: 2,
      name: "Fresh Strawberry (50kg)",
      image: "https://via.placeholder.com/150",
      sold: "200 sold",
      price: "$67.50",
    },
    {
      id: 3,
      name: "Organic Spinach (250kg)",
      image: "https://via.placeholder.com/150",
      sold: "156 sold",
      price: "$23.60",
    },
    {
      id: 4,
      name: "Organic Spinach (250kg)",
      image: "https://via.placeholder.com/150",
      sold: "140 sold",
      price: "$23.60",
    },
  ],
};
